### ISSUE TITLE
Buggy Section Offsets with LTO

### ISSUE THREAD

**Issue by CryZe** [CryZe/romhack-compiler#1]
It looks like we don't point to the proper symbol offset if we are pointing to an external (other .o file) symbol. This doesn't happen with LTO, as there's more or less only one compilation unit. However even with LTO it could happen.

**Comment by hallcristobal** [comment]
Fixed in latest commit?

**Comment by CryZe** [comment]
Oh, haha, yeah that‘s the exact bug.
